@startuml
start
:{{\nsalt\n{[Login with Github]\n}\n}};
-> Successful Login;
:{{\nsalt\n{^"Dashboard"\n\n DEPLOY APP\n\n[From Github]|[Upload Files]\n}\n}};
-> Select Code Repo/Upload Files;
:{{\nsalt\n{^"Scan the code"\n[X]Language\n[X]Framework\n[X]Config files\n[X]Environment variables\n[X]Build files if any}\n}};
:Prepare Dockerfile for Build Stage after code scan;
:Upload code + Dockerfile to Cloud Storage;
:Publish the event to Pub/Sub Queue;
@enduml
